# Generated by Django 4.1.1 on 2023-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_emp',
            field=models.CharField(default='Y', max_length=200),
        ),
    ]
