# Generated by Django 4.1.1 on 2023-02-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_employee_is_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
